In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
from google.colab import files
uploaded=files.upload()

Saving Mall_Customers.csv to Mall_Customers (1).csv

In [9]:
df=pd.read_csv('/content/Mall_Customers.csv')

In [10]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

In [12]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [13]:
df.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [14]:
df = df.drop("CustomerID", axis=1)

In [16]:
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
plt.scatter(df["Annual Income (k$)"],
            df["Spending Score (1-100)"],
            c=clusters,
            cmap="viridis",
            s=80)

plt.xlabel("Annual Income (k$)")
plt.ylabel("Spending Score (1-100)")
plt.title("K-Medoids Clustering")
plt.colorbar(label="Cluster")
plt.show()

NameError: name 'clusters' is not defined

In [15]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["Gender"] = le.fit_transform(df["Gender"])   # Male=1, Female=0

In [10]:
df["Income_per_Age"] = df["Annual Income (k$)"] / (df["Age"] + 1)

df["Spending_Income_Ratio"] = df["Spending Score (1-100)"] / (df["Annual Income (k$)"] + 1)

df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[0, 25, 40, 60, 100],
    labels=[0, 1, 2, 3]
).astype(int)

df["Customer_Value"] = (
    df["Annual Income (k$)"] *
    df["Spending Score (1-100)"]
) / 100

In [11]:
df.shape

(200, 8)

In [12]:
df.head()

,Gender,Age,Annual Income (k$),Spending Score (1-100),Income_per_Age,Spending_Income_Ratio,Age_Group,Customer_Value
0,1,19,15,39,0.750000,2.437500,0,5.85
1,1,21,15,81,0.681818,5.062500,0,12.15
2,0,20,16,6,0.761905,0.352941,0,0.96
3,0,23,16,77,0.666667,4.529412,0,12.32
4,0,31,17,40,0.531250,2.222222,1,6.80

In [19]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(df)

In [21]:
!pip uninstall -y numpy scikit-learn-extra # Uninstall existing versions to avoid conflicts
!pip install scikit-learn-extra

Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4
Found existing installation: scikit-learn-extra 0.3.0
Uninstalling scikit-learn-extra-0.3.0:
  Successfully uninstalled scikit-learn-extra-0.3.0
Collecting scikit-learn-extra
  Using cached scikit_learn_extra-0.3.0-cp312-cp312-linux_x86_64.whl
Collecting numpy>=1.13.3 (from scikit-learn-extra)
  Downloading numpy-2.5.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: scipy>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from scikit-learn-extra) (1.16.3)
Requirement already satisfied: scikit-learn>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn-extra) (1.6.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.23.0->scikit-learn-extra) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.23.0->scikit-learn-extra) (3.6.0)
Downloading numpy-2.5.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 56.5 MB/s eta 0:00:00
Installing collected packages: numpy, scikit-learn-extra
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.5.0 which is incompatible.
Successfully installed numpy-2.5.0 scikit-learn-extra-0.3.0

In [20]:
!pip uninstall -y numpy scikit-learn-extra
!pip install numpy==1.26.4
!pip install scikit-learn-extra==0.3.0

Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4
Found existing installation: scikit-learn-extra 0.3.0
Uninstalling scikit-learn-extra-0.3.0:
  Successfully uninstalled scikit-learn-extra-0.3.0
Collecting numpy==1.26.4
  Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
Installing collected packages: numpy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
shap 0.52.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4

Collecting scikit-learn-extra==0.3.0
  Using cached scikit_learn_extra-0.3.0-cp312-cp312-linux_x86_64.whl
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from scikit-learn-extra==0.3.0) (1.26.4)
Requirement already satisfied: scipy>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from scikit-learn-extra==0.3.0) (1.16.3)
Requirement already satisfied: scikit-learn>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn-extra==0.3.0) (1.6.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.23.0->scikit-learn-extra==0.3.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.23.0->scikit-learn-extra==0.3.0) (3.6.0)
Installing collected packages: scikit-learn-extra
Successfully installed scikit-learn-extra-0.3.0

In [22]:
from sklearn_extra.cluster import KMedoids

In [23]:
!pip install kmedoids

Requirement already satisfied: kmedoids in /usr/local/lib/python3.12/dist-packages (0.5.5)

In [24]:
import kmedoids

In [25]:
X = df.drop("Cluster", axis=1, errors="ignore")

In [26]:
X = df.copy()

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test = train_test_split(
    X,
    test_size=0.2,
    random_state=42
)

from sklearn_extra.cluster import KMedoids

kmedoids = KMedoids(
    n_clusters=5,
    random_state=42
)

kmedoids.fit(X_train)

train_clusters = kmedoids.predict(X_train)
test_clusters = kmedoids.predict(X_test)

In [28]:
from sklearn_extra.cluster import KMedoids

kmedoids = KMedoids(
    n_clusters=5,
    random_state=42
)

clusters = kmedoids.fit_predict(X)

In [30]:
from sklearn.metrics import silhouette_score

score = silhouette_score(X, clusters)

print("Silhouette Score:", score)

Silhouette Score: 0.4319220539571975

In [32]:
from sklearn_extra.cluster import KMedoids
from sklearn.metrics import silhouette_score

for k in range(2, 11):
    model = KMedoids(n_clusters=k, random_state=42)
    labels = model.fit_predict(X)
    score = silhouette_score(X, labels)
    print(f"k = {k}, Silhouette Score = {score:.4f}")

k = 2, Silhouette Score = 0.3035
k = 3, Silhouette Score = 0.2711
k = 4, Silhouette Score = 0.3018
k = 5, Silhouette Score = 0.4319
k = 6, Silhouette Score = 0.4078
k = 7, Silhouette Score = 0.3664
k = 8, Silhouette Score = 0.3788
k = 9, Silhouette Score = 0.3779
k = 10, Silhouette Score = 0.3653

In [33]:
from sklearn.metrics import silhouette_score

score = silhouette_score(X, clusters)

print("Silhouette Score:", score)

Silhouette Score: 0.4319220539571975

In [36]:
from sklearn_extra.cluster import KMedoids
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Define X_scaled locally for this cell, as per JhCRboa0UwbK
temp_X_for_scaling = df[["Annual Income (k$)", "Spending Score (1-100)"]]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(temp_X_for_scaling)

best_score = -1
best_k = 2

for k in range(2, 11):
    model = KMedoids(n_clusters=k, random_state=42)
    labels = model.fit_predict(X_scaled)
    score = silhouette_score(X_scaled, labels)
    print(f"k={k}, Score={score:.4f}")

    if score > best_score:
        best_score = score
        best_k = k

print("\nBest K:", best_k)
print("Best Score:", best_score)

k=2, Score=0.2876
k=3, Score=0.3764
k=4, Score=0.4930
k=5, Score=0.4476
k=6, Score=0.1923
k=7, Score=0.4073
k=8, Score=0.3712
k=9, Score=0.3521
k=10, Score=0.3515

Best K: 4
Best Score: 0.49301598881553493

In [37]:
X = df[["Annual Income (k$)", "Spending Score (1-100)"]]

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [38]:
from sklearn.metrics import silhouette_score

score = silhouette_score(X, clusters)

print("Silhouette Score:", score)

Silhouette Score: 0.5063636535071422